import type { Metadata } from "next";
import { Geist, Geist_Mono, Black_Ops_One, Barlow_Condensed, Barlow } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const blackOpsOne = Black_Ops_One({
  weight: "400",
  variable: "--font-black-ops",
  subsets: ["latin"],
});

const barlowCondensed = Barlow_Condensed({
  weight: ["400", "600", "700"],
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
});

const barlow = Barlow({
  weight: ["400", "500"],
  variable: "--font-barlow",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${blackOpsOne.variable} ${barlowCondensed.variable} ${barlow.variable} antialiased`}
      >
        <header style={{ position: "fixed", top: 12, right: 12, zIndex: 60 }}>
          <Link href="/endingpage" className="px-3 py-2 rounded-md bg-violet-700/80 text-white text-sm font-[var(--font-barlow-condensed)]">Results</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
